### ISSUE TITLE
建议恢复语音功能

### ISSUE THREAD

**Issue by SoraKasvgano** [iamwyh2019/custom-HoshinoBot#1]
https://github.com/Mrs4s/go-cqhttp

已支持
AMR 和silk格式

**Comment by SoraKasvgano** [comment]
另外本项目好像缺少config_example文件夹
![捕获](https://user-images.githubusercontent.com/8521327/92090549-22d5be80-ee02-11ea-9b00-70a7354af9f0.JPG)

在启动时报错

**Comment by SoraKasvgano** [comment]
![das](https://user-images.githubusercontent.com/8521327/92091337-359cc300-ee03-11ea-900a-b19e65887faf.JPG)

**Comment by iamwyh2019** [comment]
您好：感谢您的issue。

1. 关于语音功能，这个项目的`R.py`里**一直保留有**发语音的接口，您可以在res文件夹下新建rec文件夹（与img文件夹同级），将语音文件放在里面，在代码里以`R.rec(文件名).cqcode`调用；示例可参照`groupmaster/chat.py`里被注释的部分。
2. 关于config_example文件夹，由于这个项目只是作者自建机器人的实时开源，并非原版HoshinoBot的一个修改分发版，因此没有包含该文件夹。您可以从原版项目下载。具体参见README。
3. 您提供的两个报错，前者是python没有安装nonebot模块，可用pip安装；后者是访问权限不足，请检查该文件是否只读，及您的账户是否有权限修改该文件；必要时可用管理员账户运行。

希望这些能够帮到您。

**Comment by SoraKasvgano** [comment]
> 您好：感谢您的issue。
> 
> 1. 关于语音功能，这个项目的`R.py`里**一直保留有**发语音的接口，您可以在res文件夹下新建rec文件夹（与img文件夹同级），将语音文件放在里面，在代码里以`R.rec(文件名).cqcode`调用；示例可参照`groupmaster/chat.py`里被注释的部分。
> 2. 关于config_example文件夹，由于这个项目只是作者自建机器人的实时开源，并非原版HoshinoBot的一个修改分发版，因此没有包含该文件夹。您可以从原版项目下载。具体参见README。
> 3. 您提供的两个报错，前者是python没有安装nonebot模块，可用pip安装；后者是访问权限不足，请检查该文件是否只读，及您的账户是否有权限修改该文件；必要时可用管理员账户运行。
> 
> 希望这些能够帮到您。

啊这，非常感谢

**Comment by SoraKasvgano** [comment]
啊这，打扰您了
按以下修改后 在测试的时候提示  [不支持的方法] ，如果您哪天也改用 https://github.com/Mrs4s/go-cqhttp 这个的话可否方便研究一下，感觉比miraigo这些要方便许多。

看了一下CQ码是[CQ:record]  不知道如何修改= =

`hentai_audio=(".......你想在这里做什么？.amr","不能理解......不能理解......不能理解......amr")
roar_audio=("刷刷刷......刷刷刷.......amr","刷牙.amr","刷牙2.amr")
song_audio=("对吧！谁叫我是个高性能机器人呢嗯哼！.amr","呜呜......我好可怜.amr","眼泪也会在高兴的时候流呢.amr")

@sv.on_fullmatch(('变态','我是变态','我是绅士','变态可疑分子','可疑分子'))
async def chat_hentai(bot,ev):
    rec=random.choice(hentai_audio)
    await bot.send(ev,R.rec(rec).cqcode)

@sv.on_fullmatch(('娇喘',))
async def chat_roar(bot,ev):
    rec=random.choice(roar_audio)
    await bot.send(ev,R.rec(rec).cqcode)

@sv.on_fullmatch(('唱歌','唱首歌','来首歌','来唱首歌'), only_to_me=True)
async def sing(bot,ev):
    rec=random.choice(song_audio)
    await bot.send(ev,R.rec(rec).cqcode)


@sv.on_fullmatch(('再见','拜拜'),only_to_me=True)
async def farewell(bot,ev):
    await bot.send(ev,"拜拜~",at_sender=True)
`

**Comment by iamwyh2019** [comment]
您好。我们已经切换到go-cqhttp框架了，语音功能可以正常使用。您遇到的提示“[不支持的方法]”是因为您使用了base64协议。请更换为file或http协议。
现有的通过base64协议发送语音的方案需要引入pydub库和ffmpeg支持，我认为这并不是一个好方案，因此没有加入。

**Comment by SoraKasvgano** [comment]
> 您好。我们已经切换到go-cqhttp框架了，语音功能可以正常使用。您遇到的提示“[不支持的方法]”是因为您使用了base64协议。请更换为file或http协议。
> 现有的通过base64协议发送语音的方案需要引入pydub库和ffmpeg支持，我认为这并不是一个好方案，因此没有加入。

啊这 感谢，是base64问题，file也不行换成http协议可以了
